In [1]:
from twi_ksvd.omp import OMP
import numpy as np

## Test and usage of OMP

### Syntethic data

In [9]:
p = 10
K = 100
N = 100
x = np.ones(p)
X = np.random.random((p, N))
D = np.random.random((p, K))

### Test

In [3]:
alpha = OMP(x, D, 3)

np.linalg.norm(x - D @ alpha)

c:\users\paple\documents\3a\mva\twi-ksvd\src\twi_ksvd\omp.py:44: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  alpha_partial = lstsq(D_partial, x)[0]


0.39635663361027346

## Test and usage of COSTW

In [4]:
from twi_ksvd.costw import COSTW

t1 = np.arange(20)
t2 = np.arange(10)


x1 = np.cos(t1)
y1 = np.cos(2*t2)

costw, delta = COSTW(x1,y1)

In [5]:
delta

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Test and usage of TWI-OMP

In [6]:
from twi_ksvd.omp import TWI_OMP

D_list = [D[:,j] for j in range(D.shape[1])]

alpha, alignments = TWI_OMP(x, D_list, 3)

c:\users\paple\documents\3a\mva\twi-ksvd\src\twi_ksvd\omp.py:102: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  alpha_partial = lstsq(D_partial, x)[0]


In [7]:

approx = np.zeros_like(x)

for j in range(len(D_list)):
    if alpha[j] != 0:
        approx += alpha[j] * D_list[j][alignments[:, j]]

np.linalg.norm(x - approx)

2.1065000811460206e-15

## Test and usage of kSVD

In [10]:
from twi_ksvd.ksvd import kSVD
model = kSVD( 10)
tau = 3
model. fit(X,D,tau )

0


c:\users\paple\documents\3a\mva\twi-ksvd\src\twi_ksvd\omp.py:44: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  alpha_partial = lstsq(D_partial, x)[0]


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
Maximum number of iteration reached : 20


(array([[-7.44918308e+15, -1.16764582e+16,  1.35127070e+13, ...,
          6.24754610e+14, -1.24719174e+13,  7.83651237e+14],
        [-7.44918308e+15, -1.16764582e+16,  1.35127070e+13, ...,
          6.24754610e+14, -1.24719174e+13,  7.83651237e+14],
        [-7.44918308e+15, -1.16764582e+16,  1.35127070e+13, ...,
          6.24754610e+14, -1.24719174e+13,  7.83651237e+14],
        ...,
        [-7.44918308e+15, -1.16764582e+16,  1.35127070e+13, ...,
          6.24754610e+14, -1.24719174e+13,  7.83651237e+14],
        [-7.44918308e+15, -1.16764582e+16,  1.35127070e+13, ...,
          6.24754610e+14, -1.24719174e+13,  7.83651237e+14],
        [-7.44918308e+15, -1.16764582e+16,  1.35127070e+13, ...,
          6.24754610e+14, -1.24719174e+13,  7.83651237e+14]]),
 array([[-3.68723339e-01, -3.16208655e-01,  2.92674901e-01,
         -2.97882982e-01, -2.98489327e-01, -2.98660525e-01,
         -2.98739162e-01, -2.99093999e-01, -2.99313236e-01,
         -3.00649697e-01,  8.87673723e-01,  9.188